spring:
  application:
    name: assetflow-trade-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://sothrose:sothrose@assetflow-trade-mongo:27017/trades}
      database: trades
server:
  port: ${SERVER_PORT:8084}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:assetflow-kafka:9092}
  topic:
    trade-created: trade-created
  retries: 5
  retries-backoff-in-ms: 1000

market-data-service:
  base-url: ${MARKET_DATA_SERVICE_BASE_URL:http://assetflow-market-data-service:8083}

resilience4j.circuitbreaker:
  instances:
    marketDataService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.reactive.function.client.WebClientRequestException
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - java.net.ConnectException
        - java.lang.RuntimeException

resilience4j.bulkhead:
  instances:
    marketDataService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 20

resilience4j.thread-pool-bulkhead:
  instances:
    marketDataService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      keepAliveDuration: 20ms

resilience4j.retry:
  instances:
    marketDataService:
      maxRetryAttempts: 5
      waitDuration: 10000
      retry-exceptions:
        - org.springframework.web.reactive.function.client.WebClientRequestException
        - java.util.concurrent.TimeoutException
        - java.net.ConnectException
        - java.lang.RuntimeException

resilience4j.ratelimiter:
  instances:
    marketDataService:
      timeoutDuration: 1000ms
      limitRefreshPeriod: 5000
      limitForPeriod: 5

resilience4j.timelimiter:
  instances:
    marketDataService:
      timeoutDuration: 2s
      cancelRunningFuture: true
