spring:
  application:
    name: assetflow-market-data-aggregator
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: assetflow
  redis:
    host: assetflow-redis
    port: 6379
    password: 
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: "env,configprops,health"
