spring:
  application:
    name: assetflow-market-data-aggregator
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: assetflow
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:} 
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: "env,configprops,health"
